name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        # os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: lint deps
        uses: EmbarkStudios/cargo-deny-action@v1
      - name: build
        run: cargo build --release
